Repository LikeLion-FE-Final-Project03/car-zip, pull requests merged in 2023-03, with the labels that each got.

#24 [#18] [FEATURE] 사이드바 마크업 및 스타일링
  package-lock.json
  package.json
  public/assets/icons/icon-prev.svg
  public/assets/icons/index.js
  public/assets/images/index.js
  public/assets/images/logo.png
  public/assets/images/logo.svg
  src/App.jsx
  src/components/Sidebar/Sidebar.jsx
  src/pages/Bookmark.jsx
  src/pages/SidebarTest.jsx
  src/pages/VeiwReview.jsx
Labels: ✨feature

#32 [#20] [FEATURE] 메인화면 지도 관련 기능
  index.html
  package-lock.json
  package.json
  public/assets/icons/icon-list.svg
  public/assets/icons/icon-location.svg
  public/assets/icons/icon-menu.svg
  public/assets/icons/icon-search-btn.svg
  public/assets/icons/index.js
  src/App.css
  src/components/KakaoMap.jsx
  src/components/ParkingLotListButton.jsx
  src/components/SearchBar.jsx
  src/pages/Main.jsx
  src/styles/theme.js
  vite.config.js
Labels: ✨feature

#50 [#19] [FEATURE] 리뷰 조회, 작성 마크업 및 스타일링
  src/components/Review/ReviewBox.jsx
Labels: 🔨enhancement

#61 [#58] 주차장 데이터를 가져와 상세페이지에 붙이기
  package-lock.json
  public/assets/icons/icon-favorite.svg
  src/components/CopyButton.jsx
  src/components/FavoriteButton.jsx
  src/components/TagItem.jsx
  src/components/UtilButton.jsx
  src/components/ZipDetail/Header.jsx
  src/components/ZipDetail/InfoMore.jsx
  src/components/ZipDetail/InfoZip.jsx
  src/components/ZipDetail/RecentUpdate.jsx
  src/components/ZipDetail/ZipDetailWrapper.jsx
  src/pages/FeeCalculator.jsx
  src/pages/ZipDetail.jsx
Labels: ✨feature

#60 [#55] [FEATURE] 로그인 페이지의 '다음에 하기' 익명 로그인 기능 구현 #59
  .firebaserc
  firebase.json
  firestore.indexes.json
  firestore.rules
  index.html
  package-lock.json
  src/App.jsx
  src/Firebase.js
  src/pages/Login.jsx
  storage.rules
Labels: ✨feature

#51 [#18][#19][FEATURE] 사이드바, 리뷰 작성 페이지 반응형에 맞춘 사이즈 변경
  firebase-config.js
  package-lock.json
  package.json
  public/assets/icons/button-review-delete.svg
  public/assets/icons/index.js
  src/components/Review/ReviewBox.jsx
  src/components/Sidebar/Sidebar.jsx
  src/pages/NewReview.jsx
Labels: 🔨enhancement

#65 [#42] 상세페이지 해당 주차장으로 길찾기
  src/components/UtilButton.jsx
  src/components/ZipDetail/InfoZip.jsx
  src/pages/ZipDetail.jsx
Labels: ✨feature

#67 [#45] [✨FEATURE] 메뉴 바 클릭 시 사이드 메뉴 슬라이딩
  src/App.css
  src/App.jsx
  src/components/ParkingLotListButton.jsx
  src/components/SearchBar.jsx
  src/components/Sidebar/Sidebar.jsx
  src/pages/Main.jsx
  src/pages/SidebarTest.jsx
Labels: ✨feature

#68 [#55] [FEATURE] 깃헙 소셜 로그인 기능 추가 및 기타 소셜 로그인 버튼에 알림 추가
  package-lock.json
  package.json
  public/assets/images/login/github.svg
  src/pages/Login.jsx
Labels: ✨feature

#70 [#33][FEATURE] 리뷰 CRUD 구현 완료
  package-lock.json
  package.json
  public/assets/images/index.js
  public/assets/images/review-gray-notrecommend.svg
  public/assets/images/review-gray-recommend.svg
  src/App.jsx
  src/components/Review/ReviewBox.jsx
  src/pages/EditReview.jsx
Labels: ✨feature

#74 [#71][FEATURE] 리뷰 작성 시 로그인 유저 정보 저장, 로그인한 유저가 작성한 리뷰만 조회
  src/components/Review/ReviewBox.jsx
  src/pages/EditReview.jsx
  src/pages/Mypage.jsx
  src/pages/NewReview.jsx
Labels: 🐛bug, ✨feature

#77 [#64][FEATURE] 리뷰 세부 옵션 추가
  src/components/Review/ReviewBox.jsx
  src/pages/EditReview.jsx
  src/pages/Mypage.jsx
  src/pages/NewReview.jsx
Labels: 🐛bug, 🔨enhancement

#81 [:bug: bug] 사이드바 뒤로가기 버튼 수정
  src/components/Sidebar/Sidebar.jsx
Labels: 🐛bug

#83 [#82] [:bug: bug] useNavigate 이용하여 사이드바 메뉴 링크 수정
  src/components/Sidebar/Sidebar.jsx
Labels: 🐛bug

#87 [#75][BUG] 주차장 코드를 가지고 주차장명을 가져올 때 발생한 버그 해결
  src/components/Review/DetailReview.jsx
  src/components/Review/ReviewBox.jsx
  src/components/ZipDetail/Review.jsx
  src/pages/EditReview.jsx
  src/pages/Mypage.jsx
  src/pages/NewReview.jsx
  src/pages/ZipDetail.jsx
Labels: 🐛bug, 🔨enhancement

#88 [#47] [FEATURE] 주차장 선택 시 해당 주차장의 바텀 시트 띄우기
  index.html
  src/App.css
  src/components/KakaoMap.jsx
  src/components/ParkingLotBottomSheet.jsx
  src/components/ParkingLotListButton.jsx
  src/components/getDB/ReadDB.js
  src/pages/Main.jsx
Labels: ✨feature

#91 [FEATURE] 마이페이지에 로그인한 사용자의 이름 띄우기
  src/pages/Mypage.jsx
Labels: 🔨enhancement, ✨feature

#96 [#75][🎨style] 상세페이지 리뷰 작성 버튼 이미지 추가
  public/assets/images/index.js
  public/assets/images/review-write-btn.svg
  src/components/ZipDetail/Review.jsx
Labels: 🔨enhancement

#97 [#92] [BUG] 마커 클릭 시 바텀시트 열고 닫히는 부분 수정
  src/App.css
  src/components/KakaoMap.jsx
Labels: 🐛bug

#99 [#98][FEATURE] 뒤로가기 기능 추가, 리뷰 삭제 시 뜨는 모달창 수정
  src/components/Review/ReviewBox.jsx
  src/pages/EditReview.jsx
  src/pages/Mypage.jsx
  src/pages/NewReview.jsx
Labels: 🔨enhancement, ✨feature

#101 [#92] [BUG] 마커 클릭 시 디자인 수정
  src/components/KakaoMap.jsx
Labels: 🐛bug
